### ISSUE TITLE
This project SUCKS

### ISSUE THREAD

**Issue by liuggio** [segmentio/analytics-magento#84]
A lot of bugs, lot of erros,
I place a PR fixing a MAJOR bug nobody accepted.
now we just discovered that on logout the website is broken,
please write on the readme that this project "sucks"
and is not ready for production.

Quality code =  mediocre
Support = inexistent

**Comment by sperand-io** [comment]
hey @liuggio, thanks for the feedback. Frankly, no argument here. I'm really sorry for the painful experience. 

We're exploring options for finding a contractor to help us maintain the plugin, or would be happy to provide commit rights to some dedicated community maintainers who are better equipped to handle these PRs. As is probably obvious, we're not Magento (or PHP) experts, and the low interest/adoption of this project have been such that all our focus goes towards our core product rather than this plugin. 

If you know of anyone available looking for some extra $$, please let me know! `chris[dot]sperandio[at]segment[dot]com`
